package org.firstinspires.ftc.teamcode.Competition.IntoTheDeep.Gold10219.Controls.Auto.Pathing.Paths.Blue;

public enum BluePathStates {
    toChambers1,
    chambers1Heading,
    holdChambers1,
    chambers1Timeout,
    toSample1,
    holdSample1,
    toObservation1,
    holdObservation1,
    observation1Timeout,
    alignObservation1,
    approach1,
    approach1Timeout,
    grabSpecimen1,
    grabSpecimen1Timeout,
    toSample2,
    holdSample2,
    toObservation2,
    holdObservation2,
    observation2Timeout,
    toChambers2,
    holdChambers2,
    chambers2Timeout,
    toObservation3,
    holdObservation3,
    observation3Timeout,
    toChambers3,
    holdChambers3,
    chambers3Timeout,
    toObservation4,
    holdObservation4,
    observation4Timeout,
    toChambers4,
    holdChambers4,
    chambers4Timeout
}
